### ISSUE TITLE
⚠️ Chave de API exposta no repositório!

### ISSUE THREAD

**Issue by lucasbrasantos** [apaolaoliveira/GifSearchWeb#1]
### ⚠️ Chave de API exposta no repositório

Olá! Tudo bem?

Percebi que sua chave de API está exposta no arquivo:  
**`GifSearchWeb/src/javascript/GiphyModule/api-key.js`**, definida como:

```javascript
export const API_KEY = 'sua-chave-aqui';
```

Isso pode trazer riscos de segurança, já que qualquer pessoa que acessar o repositório pode visualizar e usar essa chave, resultando em possíveis usos indevidos e cobranças inesperadas.

### Sugestão para proteger a chave com GitHub Actions:

Como você está utilizando **GitHub Pages** com deploy via **GitHub Actions**, você pode armazenar a chave de API como um **GitHub Secret** e injetá-la dinamicamente no build. Aqui está um passo a passo:

1. **Adicione a chave como um Secret no GitHub:**
   - Acesse o repositório no GitHub.
   - Vá em: `Settings > Secrets and variables > Actions > New repository secret`.
   - Crie um Secret chamado `GIPHY_API_KEY` e cole sua chave de API lá.

2. **Modifique o workflow do GitHub Actions para injetar a chave no código:**
   
   No seu arquivo de workflow (`.github/workflows/deploy.yml` ou similar), você pode adicionar um passo para substituir a chave diretamente durante o build:

   ```yaml
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3

     - name: Set API key dynamically
       run: echo "export const API_KEY = '${{ secrets.GIPHY_API_KEY }}';" > GifSearchWeb/src/javascript/GiphyModule/api-key.js
       
     - name: Deploy to GitHub Pages
       uses: actions/deploy-pages@v1
       with:
         # Configurações específicas do deploy
   ```

3. **Revogue a chave atual e gere uma nova:**
   - Como a chave foi exposta, recomendo que você a invalide e crie uma nova antes de aplicar essa solução.

### Considerações:
- Armazenar chaves diretamente no front-end sempre apresenta algum risco, pois elas podem ser acessadas via ferramentas de desenvolvedor. O ideal seria criar um backend para gerenciar as chamadas sensíveis.
- Se precisar de ajuda para ajustar o workflow ou implementar a solução, estou à disposição! 😊

Apesar disso, o projeto está bem bacana! Parabéns pelo trabalho!
